### ISSUE TITLE
Diamond hammer doesn't 3x3x3 like tooltip says

### ISSUE THREAD

**Issue by crzyblue** [ErrorMikey/JustHammers#13]
Using diamond hammer only does a 3x3, it doesn't do the 3 deep or 3x3x3 as the tooltip says.
![2023-11-22_20 26 34](https://github.com/ErrorMikey/JustHammers/assets/82949784/d506d396-aad7-4944-a66f-80c8c9ffdaa0)

**Comment by MichaelHillcox** [comment]
Stupid tooltips, what version is this for?

**Comment by MichaelHillcox** [comment]
If this was an issue, it definitely isn't anymore :D
