### ISSUE TITLE
Creative mode Fabric

### ISSUE THREAD

**Issue by prshs70** [ErrorMikey/JustHammers#16]
I have both Fabric and Forge 1.20.1 installed, in forge you are able to break 3by3 in creative
but not so in fabric, is this a fabric thing?

**Comment by MichaelHillcox** [comment]
Yeah, this was an oversight of how I implemented the creative behaviour. I'll have an update going out today some time

**Comment by MichaelHillcox** [comment]
Fixed in the latest release for 1.19 and 1.20+
