### ISSUE TITLE
Please allow 3rd party launchers to download this mode

### ISSUE THREAD

**Issue by totoltetl** [ErrorMikey/JustHammers#2]
3rd party launchers can't download this mod as part of a modpack, would be great if you could enable that.

related: https://github.com/ErrorMikey/KubeUtils/issues/1 https://github.com/ErrorMikey/AcceleratedDecay/issues/1

**Comment by Rushmead** [comment]
"no." - Mikey 21st January 2023 23:36 GMT

**Comment by MichaelHillcox** [comment]
Now yes, have fun. It's also on modrinth. Same as KubeUtils and AcceleratedDecay
