### ISSUE TITLE
wondering if 1.19.3 for fabric is coming?

### ISSUE THREAD

**Issue by JustMeGa96** [ErrorMikey/JustHammers#3]
As the title says. And if you need help would like to offer my assistance in updating the mod.

**Comment by MichaelHillcox** [comment]
Maybe? It should be pretty easy to port to that version. I wanna get some fixes in before that though.

**Comment by MichaelHillcox** [comment]
Yeah, unlikely for this one. 1.19.3 is basically dead. If anyone want's to PR it. I'd be happy to accept it.
