### ISSUE TITLE
Tool tips don't work [Fabric]

### ISSUE THREAD

**Issue by Sickelmo83** [ErrorMikey/JustHammers#4]
![hammers](https://user-images.githubusercontent.com/7932564/222523123-92499708-35bc-4bf4-ad47-fb301847fe7c.png)

They still work as intended. The tool tips are just the same for every hammer "Mines a {0}x{0}x{1} area".

Version:
fabric-api-0.75.1+1.19.2
architectury-6.5.69-fabric
justhammers-fabric-1.0.0+mc1.19.2

**Comment by MichaelHillcox** [comment]
This should have been fixed in the 1.0.1 release :+1:
