### ISSUE TITLE
Forge 1.19.2 tooltips are wrong

### ISSUE THREAD

**Issue by Zoofule** [ErrorMikey/JustHammers#5]
Hey, It isn't a big deal, but some of the tooltips are wrong for forge 1.19.2

version: justhammers-forge-1.0.0+mc1.19.2

![May_10_#696(519x396)](https://github.com/ErrorMikey/JustHammers/assets/3208723/5532deb8-a3ba-440b-b825-fe9be446e543)
![Minecraft_1 19 2_-_Singleplayer_javaw_May_10_#699 (522x284)](https://github.com/ErrorMikey/JustHammers/assets/3208723/a2e0f81a-a8b9-4ce7-99c4-7a58f1988d60)
![Minecraft_1 19 2_-_Singleplayer_javaw_May_10_#698 (536x282)](https://github.com/ErrorMikey/JustHammers/assets/3208723/fdb0eaa5-3b0d-47e9-be18-6d97b39b464f)
![Minecraft_1 19 2_-_Singleplayer_javaw_May_10_#697 (520x282)](https://github.com/ErrorMikey/JustHammers/assets/3208723/6ec1715c-64a1-4a68-bd06-23d97652bd1b)

**Comment by Zoofule** [comment]
Obviously, the impact ones are correct, but the non-impact ones should only say they go 1 deep

**Comment by MichaelHillcox** [comment]
Should be fixed as of 1.0.1
