### ISSUE TITLE
[Bug] Blocks that are not set as pickaxe mineable do not drop items when broken.

### ISSUE THREAD

**Issue by SavageKiller13** [ErrorMikey/JustHammers#6]
Whenever I use a Hammer on any block that normally isn't mined with a pickaxe (dirt, sand, gravel, wood (any type), wool, moss, workstations, etc). 

What I expect to happen is any block that can be mined by hand that is mined by the hammer should drop the corresponding item(s).

What actually happens is all the blocks in the hammer area are destroyed and only those that are tagged as Pickaxe mineable drop their items.

A simple solution to this would be to add an if statement at [this line](https://github.com/ErrorMikey/JustHammers/blob/42f78bb2fda6f47708b9aa76d786d686e7f624c3/common/src/main/java/pro/mikey/justhammers/hammer/HammerItem.java#L151C18-L151C18) to check if the hardness of the block is lower than the max for hand. 
Another way to fix this would be to simply cancel the block break event on blocks that normally don't require a tool to drop an item.

**Comment by MichaelHillcox** [comment]
This has been fixed. Thanks for the report
